name: mindi
version: "2.1.0"
grade: stable
base: core18
summary: mindi
description: |
  Quickly convert video to audio
    Features:
    Get from web stream base.
    Use from context menu: right click on video, and select "Convert to Audio".
    Use from Applications select video.nfinement: strict
confinement: strict
parts:
  mindi:
    after: [granite, desktop-gnome-platform]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/torikulhabib/mindi.git
    override-build: |
      snapcraftctl build
        sed -i -E 's|^(Icon[^=]*)=.*|\1=/usr/share/icons/hicolor/256x256/apps/com.github.torikulhabib.mindi.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/com.github.torikulhabib.mindi.desktop
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - gettext
        - libgranite-dev
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
  granite:
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/elementary/granite.git
    override-build: |
      snapcraftctl build
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - gettext
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
apps:
  mindi:
    command: desktop-launch $SNAP/usr/bin/com.github.torikulhabib.mindi
    desktop: usr/share/applications/com.github.torikulhabib.mindi.desktop
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - ffmpeg
      - youtube-dl
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
    slots: [ dbus-mindi ]
slots:
  dbus-mindi:
    interface: dbus
    bus: session
    name: com.github.torikulhabib.mindi
plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
